# Generated by Django 3.1.7 on 2021-05-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210502_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_pt_br',
            field=models.CharField(max_length=200),
        ),
    ]
