# Generated by Django 3.1.7 on 2021-04-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description_pt_br', models.TextField(blank=True)),
                ('description_en_us', models.TextField(blank=True)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pt_br', models.CharField(max_length=250)),
                ('title_en_us', models.CharField(blank=True, max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('description_pt_br', models.TextField(blank=True)),
                ('description_en_us', models.TextField(blank=True)),
                ('key_achievement_pt_br', models.CharField(blank=True, max_length=250)),
                ('key_achievement_en_us', models.CharField(blank=True, max_length=250)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_pt_br', models.TextField(blank=True)),
                ('description_en_us', models.TextField(blank=True)),
                ('level', models.IntegerField()),
                ('icon_file_name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.skill')),
            ],
        ),
    ]
