# Generated by Django 3.1.7 on 2021-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='name_pt_br',
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en_us',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
