# Generated by Django 3.1.7 on 2021-05-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20210502_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_file_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, upload_to='skills'),
        ),
    ]
