# Generated by Django 3.1.11 on 2021-06-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20210508_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('HIGH', 'HIGH'), ('MID', 'MID'), ('LOW', 'LOW')], default='LOW', max_length=4)),
                ('description_pt_br', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='place_en_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='place_pt_br',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='relevance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.relevance'),
        ),
        migrations.AddField(
            model_name='experience',
            name='relevance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.relevance'),
        ),
        migrations.AddField(
            model_name='skill',
            name='relevance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.relevance'),
        ),
    ]
