# Generated by Django 3.1.11 on 2021-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20210601_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevance',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
