# Generated by Django 3.1.11 on 2021-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_relevance_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_pt_br',
        ),
        migrations.AddField(
            model_name='course',
            name='name_en_us',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='place_en_us',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='place_pt_br',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
